const state = {
  books: [
    { id: '1', abbr_cn: '创', name_cn: '创世纪', abbr_en: 'Gen', name_en: 'Genesis', chapters: 50, class: '1', class_name: '律法书', category: 'old' },
    { id: '2', abbr_cn: '出', name_cn: '出埃及记', abbr_en: 'Exo', name_en: 'Exotus', chapters: 40, class: '1', class_name: '律法书', category: 'old' },
    { id: '3', abbr_cn: '利', name_cn: '利未记', abbr_en: 'Lev', name_en: 'Leviticus', chapters: 27, class: '1', class_name: '律法书', category: 'old' },
    { id: '4', abbr_cn: '民', name_cn: '民数记', abbr_en: 'Num', name_en: 'Numbers', chapters: 36, class: '1', class_name: '律法书', category: 'old' },
    { id: '5', abbr_cn: '申', name_cn: '申命记', abbr_en: 'Deu', name_en: 'Deuteronomy', chapters: 34, class: '1', class_name: '律法书', category: 'old' },
    { id: '6', abbr_cn: '书', name_cn: '约书亚书', abbr_en: 'Jos', name_en: 'Joshua', chapters: 24, class: '2', class_name: '历史书', category: 'old' },
    { id: '7', abbr_cn: '士', name_cn: '土师记', abbr_en: 'Jug', name_en: 'Judges', chapters: 21, class: '2', class_name: '历史书', category: 'old' },
    { id: '8', abbr_cn: '得', name_cn: '路得记', abbr_en: 'Rut', name_en: 'Ruth', chapters: 4, class: '2', class_name: '历史书', category: 'old' },
    { id: '9', abbr_cn: '撒上', name_cn: '撒母士记上', abbr_en: '1Sa', name_en: 'Samuel1', chapters: 31, class: '2', class_name: '历史书', category: 'old' },
    { id: '10', abbr_cn: '撒下', name_cn: '撒母士记下', abbr_en: '2Sa', name_en: 'Samuel2', chapters: 24, class: '2', class_name: '历史书', category: 'old' },
    { id: '11', abbr_cn: '王上', name_cn: '列王记上', abbr_en: '1Ki', name_en: '1Kings', chapters: 22, class: '2', class_name: '历史书', category: 'old' },
    { id: '12', abbr_cn: '王下', name_cn: '列王记下', abbr_en: '2Ki', name_en: '2Kings', chapters: 25, class: '2', class_name: '历史书', category: 'old' },
    { id: '13', abbr_cn: '代上', name_cn: '历代记上', abbr_en: '1Ch', name_en: '1Chronicles', chapters: 29, class: '2', class_name: '历史书', category: 'old' },
    { id: '14', abbr_cn: '代下', name_cn: '历代记下', abbr_en: '2Ch', name_en: '2Chronicles', chapters: 26, class: '2', class_name: '历史书', category: 'old' },
    { id: '15', abbr_cn: '拉', name_cn: '以斯拉', abbr_en: 'Ezr', name_en: 'Ezra', chapters: 10, class: '2', class_name: '历史书', category: 'old' },
    { id: '16', abbr_cn: '尼', name_cn: '尼希米记', abbr_en: 'Neh', name_en: 'Nehemiah', chapters: 13, class: '2', class_name: '历史书', category: 'old' },
    { id: '17', abbr_cn: '斯', name_cn: '以斯帖记', abbr_en: 'Est', name_en: 'Esther', chapters: 10, class: '2', class_name: '历史书', category: 'old' },
    { id: '18', abbr_cn: '伯', name_cn: '约伯记', abbr_en: 'Job', name_en: 'Job', chapters: 42, class: '3', class_name: '诗歌·智慧书', category: 'old' },
    { id: '19', abbr_cn: '诗', name_cn: '诗篇', abbr_en: 'Psm', name_en: 'Psamls', chapters: 150, class: '3', class_name: '诗歌·智慧书', category: 'old' },
    { id: '20', abbr_cn: '箴', name_cn: '箴言书', abbr_en: 'Pro', name_en: 'Proverbs', chapters: 31, class: '3', class_name: '诗歌·智慧书', category: 'old' },
    { id: '21', abbr_cn: '传', name_cn: '传道书', abbr_en: 'Ecc', name_en: 'Ecclesiastes', chapters: 12, class: '3', class_name: '诗歌·智慧书', category: 'old' },
    { id: '22', abbr_cn: '歌', name_cn: '雅歌', abbr_en: 'Son', name_en: 'Songs', chapters: 8, class: '3', class_name: '诗歌·智慧书', category: 'old' },
    { id: '23', abbr_cn: '赛', name_cn: '以赛亚书', abbr_en: 'Isa', name_en: 'Issiah', chapters: 66, class: '4', class_name: '先知书', category: 'old' },
    { id: '24', abbr_cn: '耶', name_cn: '耶利米书', abbr_en: 'Jer', name_en: 'Jeremiah', chapters: 52, class: '4', class_name: '先知书', category: 'old' },
    { id: '25', abbr_cn: '哀', name_cn: '耶利米哀歌', abbr_en: 'Lam', name_en: 'Lamentations', chapters: 5, class: '4', class_name: '先知书', category: 'old' },
    { id: '26', abbr_cn: '结', name_cn: '以西结书', abbr_en: 'Eze', name_en: 'Ezekiel', chapters: 48, class: '4', class_name: '先知书', category: 'old' },
    { id: '27', abbr_cn: '但', name_cn: '但以理书', abbr_en: 'Dan', name_en: 'Daniel', chapters: 12, class: '4', class_name: '先知书', category: 'old' },
    { id: '28', abbr_cn: '何', name_cn: '何西阿书', abbr_en: 'Hos', name_en: 'Hosea', chapters: 14, class: '4', class_name: '先知书', category: 'old' },
    { id: '29', abbr_cn: '珥', name_cn: '约珥书', abbr_en: 'Joe', name_en: 'Joel', chapters: 3, class: '4', class_name: '先知书', category: 'old' },
    { id: '30', abbr_cn: '摩', name_cn: '阿摩司书', abbr_en: 'Amo', name_en: 'Amos', chapters: 9, class: '4', class_name: '先知书', category: 'old' },
    { id: '31', abbr_cn: '俄', name_cn: '俄巴底亚书', abbr_en: 'Oba', name_en: 'Obadiah', chapters: 1, class: '4', class_name: '先知书', category: 'old' },
    { id: '32', abbr_cn: '拿', name_cn: '约拿书', abbr_en: 'Jon', name_en: 'Jonah', chapters: 4, class: '4', class_name: '先知书', category: 'old' },
    { id: '33', abbr_cn: '弥', name_cn: '弥迦书', abbr_en: 'Mic', name_en: 'Micah', chapters: 7, class: '4', class_name: '先知书', category: 'old' },
    { id: '34', abbr_cn: '鸿', name_cn: '那鸿书', abbr_en: 'Nah', name_en: 'Nahum', chapters: 3, class: '4', class_name: '先知书', category: 'old' },
    { id: '35', abbr_cn: '哈', name_cn: '哈巴谷书', abbr_en: 'Hab', name_en: 'Habakkuk', chapters: 3, class: '4', class_name: '先知书', category: 'old' },
    { id: '36', abbr_cn: '番', name_cn: '西番雅书', abbr_en: 'Zep', name_en: 'Zephaniah', chapters: 3, class: '4', class_name: '先知书', category: 'old' },
    { id: '37', abbr_cn: '该', name_cn: '哈该书', abbr_en: 'Hag', name_en: 'Haggai', chapters: 2, class: '4', class_name: '先知书', category: 'old' },
    { id: '38', abbr_cn: '亚', name_cn: '撒迦利亚书', abbr_en: 'Zec', name_en: 'Zechariah', chapters: 14, class: '4', class_name: '先知书', category: 'old' },
    { id: '39', abbr_cn: '玛', name_cn: '玛拉基书', abbr_en: 'Mal', name_en: 'Malachi', chapters: 4, class: '4', class_name: '先知书', category: 'old' },
    { id: '40', abbr_cn: '太', name_cn: '马太福音', abbr_en: 'Mat', name_en: 'Matt', chapters: 28, class: '5', class_name: '四福音', category: 'new' },
    { id: '41', abbr_cn: '可', name_cn: '马可福音', abbr_en: 'Mak', name_en: 'Mark', chapters: 16, class: '5', class_name: '四福音', category: 'new' },
    { id: '42', abbr_cn: '路', name_cn: '路加福音', abbr_en: 'Luk', name_en: 'Luke', chapters: 24, class: '5', class_name: '四福音', category: 'new' },
    { id: '43', abbr_cn: '约', name_cn: '约翰福音', abbr_en: 'Jhn', name_en: 'John', chapters: 21, class: '5', class_name: '四福音', category: 'new' },
    { id: '44', abbr_cn: '徒', name_cn: '使徒行传', abbr_en: 'Act', name_en: 'Acts', chapters: 28, class: '6', class_name: '教会历史', category: 'new' },
    { id: '45', abbr_cn: '罗', name_cn: '罗马书', abbr_en: 'Rom', name_en: 'Roman', chapters: 16, class: '7', class_name: '书信', category: 'new' },
    { id: '46', abbr_cn: '林前', name_cn: '哥林多前书', abbr_en: '1Co', name_en: '1Corinthians', chapters: 16, class: '7', class_name: '书信', category: 'new' },
    { id: '47', abbr_cn: '林后', name_cn: '哥林多后书', abbr_en: '2Co', name_en: '2Corinthians', chapters: 13, class: '7', class_name: '书信', category: 'new' },
    { id: '48', abbr_cn: '加', name_cn: '加拉太书', abbr_en: 'Gal', name_en: 'Galatians', chapters: 6, class: '7', class_name: '书信', category: 'new' },
    { id: '49', abbr_cn: '弗', name_cn: '以弗所书', abbr_en: 'Eph', name_en: 'Ephesians', chapters: 6, class: '7', class_name: '书信', category: 'new' },
    { id: '50', abbr_cn: '腓', name_cn: '腓利比书', abbr_en: 'Phl', name_en: 'Philippians', chapters: 4, class: '7', class_name: '书信', category: 'new' },
    { id: '51', abbr_cn: '西', name_cn: '歌罗西书', abbr_en: 'Col', name_en: 'Colossians', chapters: 4, class: '7', class_name: '书信', category: 'new' },
    { id: '52', abbr_cn: '帖前', name_cn: '帖前', abbr_en: '1Ts', name_en: '1Thessalonians', chapters: 5, class: '7', class_name: '书信', category: 'new' },
    { id: '53', abbr_cn: '帖后', name_cn: '帖后', abbr_en: '2Ts', name_en: '2Thessalonians', chapters: 3, class: '7', class_name: '书信', category: 'new' },
    { id: '54', abbr_cn: '提前', name_cn: '提摩太前书', abbr_en: '1Ti', name_en: '1Timothy', chapters: 6, class: '7', class_name: '书信', category: 'new' },
    { id: '55', abbr_cn: '提后', name_cn: '提摩太后书', abbr_en: '2Ti', name_en: '2Timothy', chapters: 4, class: '7', class_name: '书信', category: 'new' },
    { id: '56', abbr_cn: '多', name_cn: '提多书', abbr_en: 'Tit', name_en: 'Titus', chapters: 3, class: '7', class_name: '书信', category: 'new' },
    { id: '57', abbr_cn: '门', name_cn: '腓利门书', abbr_en: 'Phm', name_en: 'Philemon', chapters: 1, class: '7', class_name: '书信', category: 'new' },
    { id: '58', abbr_cn: '来', name_cn: '希伯来书', abbr_en: 'Heb', name_en: 'Hebrews', chapters: 13, class: '7', class_name: '书信', category: 'new' },
    { id: '59', abbr_cn: '雅', name_cn: '雅各书', abbr_en: 'Jas', name_en: 'James', chapters: 5, class: '7', class_name: '书信', category: 'new' },
    { id: '60', abbr_cn: '彼前', name_cn: '彼得前书', abbr_en: '1Pe', name_en: '1Peter', chapters: 5, class: '7', class_name: '书信', category: 'new' },
    { id: '61', abbr_cn: '彼后', name_cn: '彼得后书', abbr_en: '2Pe', name_en: '2Peter', chapters: 3, class: '7', class_name: '书信', category: 'new' },
    { id: '62', abbr_cn: '约一', name_cn: '约翰一书', abbr_en: '1Jn', name_en: '1John', chapters: 5, class: '7', class_name: '书信', category: 'new' },
    { id: '63', abbr_cn: '约二', name_cn: '约翰二书', abbr_en: '2Jn', name_en: '2John', chapters: 1, class: '7', class_name: '书信', category: 'new' },
    { id: '64', abbr_cn: '约三', name_cn: '约翰三书', abbr_en: '3Jn', name_en: '3John', chapters: 1, class: '7', class_name: '书信', category: 'new' },
    { id: '65', abbr_cn: '犹', name_cn: '犹大书', abbr_en: 'Jud', name_en: 'Jude', chapters: 1, class: '7', class_name: '书信', category: 'new' },
    { id: '66', abbr_cn: '启', name_cn: '启示录', abbr_en: 'Rev', name_en: 'Revelation', chapters: 22, class: '8', class_name: '约翰的启示', category: 'new' },
  ],
};

const getters = {
  books() {
    return state.books;
  },
  category: state => category => state.books.filter(item => item.category === category),
  book: state => abbrEn => state.books.find(item => item.abbr_en === abbrEn),
};

export default {
  state,
  getters,
};
